#!/usr/bin/env bash

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay
yay -Syyu --needed - < ~/.config/yadm/packages
systemctl enable --now docker.socket
systemctl enable --now greetd.service
systemctl enable --now pipewire-pulse.service
