format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

add_newline = false

[directory]
style = "blue"

[character]
success_symbol = "[>](blue)"
error_symbol = "[>](red)"
vimcmd_symbol = "[<](purple)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[battery]
disabled = true

[git_status]
format = "[( $conflicted$untracked$modified$staged$renamed$deleted$ahead_behind)]($style)"
style = "gray"
conflicted = "x"
untracked = "u"
modified = "m"
staged = "s"
renamed = "r"
deleted = "d"
ahead = ">"
behind = "<"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
